name: repo_viewer
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  oauth2: ^2.0.0
  flutter_secure_storage: ^5.0.2
  dartz: ^0.10.1
  dio: ^4.0.4
  flutter_hooks: ^0.18.2
  hooks_riverpod: ^1.0.3
  freezed_annotation: ^1.1.0
  webview_flutter:
  flash:
  auto_route:

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  build_runner:
  freezed:
  lint:
  auto_route_generator:

flutter:
  uses-material-design: true
